interface Window {
  __ModuleLoader__: {
    load(input: { id: string; factory: (require: (id: string) => unknown) => unknown }): void
  }
}

declare const DSH_REMOTE_CLIENT_MODULE_ID: string | undefined

const clientModuleId = typeof DSH_REMOTE_CLIENT_MODULE_ID === 'string'
  ? DSH_REMOTE_CLIENT_MODULE_ID
  : '@dsh-remote/plugin'

interface ControlResult<T = unknown> {
  ok: boolean
  value?: T
  error?: { message?: string }
}

interface RemoteStatus {
  mode: 'local' | 'remote'
  target?: { deviceId: string; name: string }
  available: boolean
  hostAuthorizationAvailable: boolean
  host?: {
    configured: boolean
    online: boolean
    error?: string
    account?: string
    accountRequired: boolean
  }
}

interface RemoteDevice {
  deviceId: string
  name: string
  platform: string
  online: boolean
}

interface PluginSettings {
  enabled?: boolean
  role?: 'host' | 'client' | 'both'
  serverUrl?: string
  forceRelay?: boolean
  logLevel?: 'debug' | 'info' | 'warn' | 'error'
  reconnect?: boolean | {
    enabled?: boolean
    initialDelayMs?: number
    maxDelayMs?: number
    jitter?: number
  }
}

interface PluginSettingsView {
  config: PluginSettings
  deviceName: string
  writable: boolean
  applies: 'restart'
  association?: PluginAssociation
  associations?: Partial<Record<'host' | 'client', PluginAssociation>>
}

interface PluginAssociation {
  method: 'account' | 'host_registration_code' | 'owned_device'
  account?: string
}

interface PluginConfigureResult {
  status: 'authorized'
  role: 'host' | 'client'
  account?: string
  settings: PluginSettingsView
}

const localeNamespace = 'dsh-remote'

const en = {
  pluginTitle: 'DeepSeek Remote',
  pluginDescription: 'Remote Host and Client connection',
  expandSettings: 'Show settings: {name}',
  collapseSettings: 'Hide settings: {name}',
  unsaved: 'Unsaved',
  associated: 'Associated',
  loadingSettings: 'Loading DeepSeek Remote settings…',
  mode: 'Mode',
  pluginMode: 'Plugin mode',
  host: 'Host',
  client: 'Client',
  authorization: 'Authorization',
  account: 'Account',
  hostRegistrationCode: 'Host registration code',
  ownedDeviceAuthorization: 'Owned device',
  authorizedOn: '{role} is authorized on {serverUrl}.',
  readOnly: 'This DSH profile does not provide writable user settings.',
  discard: 'Discard',
  save: 'Save',
  saving: 'Saving…',
  signOut: 'Sign out',
  signingOut: 'Signing out…',
  setupIntro: 'Device: {deviceName}. Authorize {role} for this Server. Changing Mode does not remove either role\'s saved registration.',
  serverUrl: 'Server URL',
  serverUrlHint: 'HTTPS origin used for account authorization and encrypted relay.',
  authorizationMethod: 'Authorization method',
  accountPassword: 'Account password',
  registrationCode: 'Registration code',
  registrationCodeHint: 'Use the one-time code generated by the signed-in Server website.',
  accountHint: 'The account must belong to the selected Server.',
  password: 'Password',
  passwordHint: 'Used only for this HTTPS authorization request and never saved.',
  modeSavedNeedsAuthorization: 'Mode saved. Authorize {role} before connecting. Existing registrations were kept.',
  modeSavedReused: 'Mode saved. Existing registration reused. Restart Harness to apply.',
  modeSavedOwnedRole: 'Mode saved. This owned device was authorized automatically. Restart Harness to apply.',
  enterRegistrationCode: 'Enter a Host registration code.',
  enterAccountPassword: 'Enter the Server account and password.',
  associationSaved: 'Associated. Restart Harness to apply.',
  signedOut: 'Signed out. Restart Harness to disconnect this mode.',
  remoteRequestFailed: 'Remote mode request failed.',
  switchTarget: 'Switch Local / Remote Harness target',
  harnessTarget: 'Harness target',
  close: 'Close',
  local: 'Local',
  remoteTarget: 'Remote · {name}',
  thisMachineLocal: 'This machine (Local)',
  noRemoteHosts: 'No authorized remote Host for this account.',
  online: 'Online',
  offline: 'Offline',
  thisMachineHost: 'This machine as Remote Host',
  connected: 'Connected',
  connectedAs: 'Connected as {account}',
  hostSignInHint: 'Sign in to authorize this Host on the selected Server.',
  checkingHost: 'Checking Host registration…',
  hostUnavailable: 'Host unavailable: {error}',
  serverAccountEmail: 'Server account email',
  serverAccountPassword: 'Server account password',
  signInRegisterHost: 'Sign in and register Host',
  signingIn: 'Signing in…',
  useRegistrationCode: 'Use registration code',
  registering: 'Registering…',
} as const

const zh: Record<keyof typeof en, string> = {
  pluginTitle: 'DeepSeek 远程连接',
  pluginDescription: '远程 Host 与 Client 连接',
  expandSettings: '展开设置：{name}',
  collapseSettings: '收起设置：{name}',
  unsaved: '未保存',
  associated: '已关联',
  loadingSettings: '正在加载 DeepSeek 远程连接设置…',
  mode: '模式',
  pluginMode: '插件模式',
  host: 'Host',
  client: 'Client',
  authorization: '授权',
  account: '账号',
  hostRegistrationCode: 'Host 注册码',
  ownedDeviceAuthorization: '自有设备',
  authorizedOn: '{role} 已在 {serverUrl} 完成授权。',
  readOnly: '此 DSH profile 不提供可写的用户设置。',
  discard: '放弃修改',
  save: '保存',
  saving: '保存中…',
  signOut: '退出授权',
  signingOut: '正在退出…',
  setupIntro: '设备：{deviceName}。请为此 Server 授权 {role}。切换模式不会删除任一角色已保存的注册信息。',
  serverUrl: 'Server 地址',
  serverUrlHint: '用于账号授权和加密中继的 HTTPS 地址。',
  authorizationMethod: '授权方式',
  accountPassword: '账号密码',
  registrationCode: '注册码',
  registrationCodeHint: '使用已登录 Server 网站生成的一次性注册码。',
  accountHint: '账号必须属于所选 Server。',
  password: '密码',
  passwordHint: '仅用于本次 HTTPS 授权请求，不会保存。',
  modeSavedNeedsAuthorization: '模式已保存。连接前请先授权 {role}；已有注册信息已保留。',
  modeSavedReused: '模式已保存并复用已有注册信息。重启 Harness 后生效。',
  modeSavedOwnedRole: '模式已保存，并已自动授权此自有设备。重启 Harness 后生效。',
  enterRegistrationCode: '请输入 Host 注册码。',
  enterAccountPassword: '请输入 Server 账号和密码。',
  associationSaved: '关联成功。重启 Harness 后生效。',
  signedOut: '已退出授权。重启 Harness 后将断开此模式。',
  remoteRequestFailed: '远程模式请求失败。',
  switchTarget: '切换本地或远程 Harness',
  harnessTarget: 'Harness 目标',
  close: '关闭',
  local: '本地',
  remoteTarget: '远程 · {name}',
  thisMachineLocal: '此设备（本地）',
  noRemoteHosts: '此账号没有已授权的远程 Host。',
  online: '在线',
  offline: '离线',
  thisMachineHost: '将此设备作为远程 Host',
  connected: '已连接',
  connectedAs: '已使用 {account} 连接',
  hostSignInHint: '登录后在所选 Server 上授权此 Host。',
  checkingHost: '正在检查 Host 注册状态…',
  hostUnavailable: 'Host 不可用：{error}',
  serverAccountEmail: 'Server 账号邮箱',
  serverAccountPassword: 'Server 账号密码',
  signInRegisterHost: '登录并注册 Host',
  signingIn: '正在登录…',
  useRegistrationCode: '使用注册码',
  registering: '正在注册…',
}

type LocaleKey = keyof typeof en
type Translate = (key: LocaleKey, params?: Record<string, string | number>) => string
interface LocalizedMessage {
  key: LocaleKey
  params?: Record<string, string | number>
}

window.__ModuleLoader__.load({
  id: clientModuleId,
  factory: require => {
    const module = { exports: {} as Record<string, unknown> }
    const React = require('react') as {
      Fragment: unknown
      createElement(type: unknown, props?: Record<string, unknown> | null, ...children: unknown[]): unknown
      useEffect(effect: () => void | (() => void), deps: unknown[]): void
      useState<T>(initial: T): [T, (value: T | ((previous: T) => T)) => void]
    }
    const inject = ['connection', 'slots', 'locale']

    function RemotePluginOptions(props: {
      control: <T>(endpoint: string, payload?: unknown) => Promise<T>
      t: Translate
    }): unknown {
      const { t } = props
      const [open, setOpen] = React.useState(false)
      const [serverUrl, setServerUrl] = React.useState('')
      const [role, setRole] = React.useState<'host' | 'client'>('host')
      const [deviceName, setDeviceName] = React.useState('')
      const [hostEnrollment, setHostEnrollment] = React.useState<'account' | 'host_registration_code'>('account')
      const [registrationCode, setRegistrationCode] = React.useState('')
      const [email, setEmail] = React.useState('')
      const [password, setPassword] = React.useState('')
      const [associations, setAssociations] = React.useState<Partial<Record<'host' | 'client', PluginAssociation>>>({})
      const [loaded, setLoaded] = React.useState(false)
      const [writable, setWritable] = React.useState(false)
      const [busy, setBusy] = React.useState(false)
      const [notice, setNotice] = React.useState<LocalizedMessage | undefined>(undefined)
      const [error, setError] = React.useState<string | undefined>(undefined)
      const [settingsView, setSettingsView] = React.useState<PluginSettingsView | undefined>(undefined)
      const persistedRole = settingsView?.config.role === 'client' ? 'client' : 'host'
      const persistedServerUrl = settingsView?.config.serverUrl ?? 'https://dsh.r2049.cn'
      const association = associations[role]
      const roleDirty = settingsView !== undefined && role !== persistedRole
      const serverDirty = settingsView !== undefined && serverUrl !== persistedServerUrl
      const authorizationDirty = email !== '' || password !== '' || registrationCode !== ''
      const draftDirty = roleDirty || serverDirty || authorizationDirty

      const applyView = (view: PluginSettingsView): void => {
        const viewRole = view.config.role === 'client' ? 'client' : 'host'
        setSettingsView(view)
        setServerUrl(view.config.serverUrl ?? 'https://dsh.r2049.cn')
        setRole(viewRole)
        setDeviceName(view.deviceName)
        setAssociations(view.associations ?? (view.association === undefined ? {} : { [viewRole]: view.association }))
        setWritable(view.writable)
        setLoaded(true)
      }

      const load = async (): Promise<void> => {
        const view = await props.control<PluginSettingsView>('settings.get')
        applyView(view)
      }

      React.useEffect(() => {
        void load().catch(reason => setError(messageOf(reason)))
      }, [])

      const save = async (event?: Event): Promise<void> => {
        event?.preventDefault()
        if (!writable) return
        setBusy(true)
        setNotice(undefined)
        setError(undefined)
        try {
          if (roleDirty && !serverDirty && association === undefined && !authorizationDirty) {
            const view = await props.control<PluginSettingsView>('settings.role.set', { role })
            applyView(view)
            setNotice(view.associations?.[role] === undefined
              ? { key: 'modeSavedNeedsAuthorization', params: { role: t(role) } }
              : { key: 'modeSavedOwnedRole' })
            return
          }
          if (roleDirty && !serverDirty && association !== undefined) {
            const view = await props.control<PluginSettingsView>('settings.role.set', { role })
            applyView(view)
            setNotice({ key: 'modeSavedReused' })
            return
          }
          if (role === 'host' && hostEnrollment === 'host_registration_code' && registrationCode.trim() === '') {
            throw new Error(t('enterRegistrationCode'))
          }
          if ((role !== 'host' || hostEnrollment === 'account') && (email.trim() === '' || password === '')) {
            throw new Error(t('enterAccountPassword'))
          }
          const result = await props.control<PluginConfigureResult>('settings.configure', {
            serverUrl,
            role,
            ...(role === 'host' && hostEnrollment === 'host_registration_code'
              ? { registrationCode }
              : { email, password }),
          })
          applyView(result.settings)
          setNotice({ key: 'associationSaved' })
          setRegistrationCode('')
          setEmail('')
          setPassword('')
        } catch (reason) {
          setError(messageOf(reason))
        } finally {
          setBusy(false)
        }
      }

      const switchRole = (nextRole: 'host' | 'client'): void => {
        if (nextRole === role) return
        setError(undefined)
        setNotice(undefined)
        setRole(nextRole)
      }

      const logout = async (): Promise<void> => {
        setBusy(true)
        setError(undefined)
        setNotice(undefined)
        try {
          const view = await props.control<PluginSettingsView>('settings.logout')
          applyView(view)
          setEmail('')
          setPassword('')
          setRegistrationCode('')
          setNotice({ key: 'signedOut' })
        } catch (reason) {
          setError(messageOf(reason))
        } finally {
          setBusy(false)
        }
      }

      const discard = (): void => {
        if (settingsView !== undefined) applyView(settingsView)
        setRegistrationCode('')
        setEmail('')
        setPassword('')
        setNotice(undefined)
        setError(undefined)
      }

      const modeSwitch = React.createElement('div', { className: 'dshRemoteRoleField' },
        React.createElement('span', { className: 'dshRemoteRoleLabel' }, t('mode')),
        React.createElement('div', { className: 'dshRemoteRoleSwitch', role: 'group', 'aria-label': t('pluginMode') },
          React.createElement('button', {
            type: 'button',
            className: role === 'host' ? 'isActive' : '',
            'aria-pressed': role === 'host',
            disabled: busy || !writable || !loaded,
            onClick: () => switchRole('host'),
          }, t('host')),
          React.createElement('button', {
            type: 'button',
            className: role === 'client' ? 'isActive' : '',
            'aria-pressed': role === 'client',
            disabled: busy || !writable || !loaded,
            onClick: () => switchRole('client'),
          }, t('client'))))

      return React.createElement('li', { className: `dshRemotePluginCard${open ? ' isOpen' : ''}` },
        React.createElement('div', { className: 'dshRemotePluginCardHeader' },
          React.createElement('button', {
            type: 'button',
            className: 'dshRemotePluginCardToggle',
            'aria-expanded': open,
            'aria-label': t(open ? 'collapseSettings' : 'expandSettings', { name: t('pluginTitle') }),
            onClick: () => setOpen(current => !current),
          },
          React.createElement('span', { className: 'dshRemotePluginCardHeading' },
            React.createElement('strong', null, t('pluginTitle')),
            React.createElement('span', null, t('pluginDescription'))),
          draftDirty
            ? React.createElement('span', { className: 'dshRemotePluginCardStatus' }, t('unsaved'))
            : association === undefined ? null : React.createElement('span', { className: 'dshRemotePluginCardStatus' }, t('associated')),
          React.createElement('span', { className: 'dshRemotePluginCardChevron', 'aria-hidden': true }, '⌄'))),
        !open ? null : React.createElement('div', { className: 'dshRemotePluginCardBody' },
          !loaded
            ? React.createElement('p', { className: 'dshRemoteSettingsState' }, error ?? t('loadingSettings'))
            : association !== undefined
              ? React.createElement('div', { className: 'dshRemoteSettings' },
        React.createElement('div', { className: 'dshRemoteSettingsTop' },
          React.createElement('div', { className: 'dshRemoteAssociation' },
            React.createElement('span', null, t(association.account === undefined ? 'authorization' : 'account')),
            React.createElement('strong', null, association.account
              ?? t(association.method === 'owned_device' ? 'ownedDeviceAuthorization' : 'hostRegistrationCode')),
            React.createElement('p', null, t('authorizedOn', { role: t(role), serverUrl }))),
          modeSwitch),
        !writable ? React.createElement('p', { className: 'dshRemoteError' }, t('readOnly')) : null,
        React.createElement('div', { className: 'dshRemoteSettingsFooter' },
          error !== undefined
            ? React.createElement('p', { className: 'dshRemoteError', role: 'alert' }, error)
            : notice === undefined ? null : React.createElement('p', { className: 'dshRemoteNotice', role: 'status' }, t(notice.key, notice.params)),
          draftDirty
            ? React.createElement(React.Fragment, null,
              React.createElement('button', { type: 'button', className: 'dshRemoteDiscard', disabled: busy, onClick: discard }, t('discard')),
              React.createElement('button', { type: 'button', className: 'dshRemoteSave', disabled: busy || !writable, onClick: () => void save() }, t(busy ? 'saving' : 'save')))
            : React.createElement('button', {
              type: 'button',
              className: 'dshRemoteDiscard',
              disabled: busy || !writable,
              onClick: () => void logout(),
            }, t(busy ? 'signingOut' : 'signOut'))))
              : React.createElement('form', { className: 'dshRemoteSettings', noValidate: true, onSubmit: (event: Event) => void save(event) },
        React.createElement('div', { className: 'dshRemoteSettingsTop' },
          React.createElement('div', { className: 'dshRemoteSettingsIntro' },
            React.createElement('p', null, t('setupIntro', { deviceName, role: t(role) }))),
          modeSwitch),
        React.createElement('div', { className: 'dshRemoteField' },
          React.createElement('label', { htmlFor: 'dsh-remote-server-url' }, t('serverUrl')),
          React.createElement('input', {
            id: 'dsh-remote-server-url',
            type: 'url',
            value: serverUrl,
            disabled: busy || !writable,
            required: true,
            placeholder: 'https://dsh.r2049.cn',
            onChange: (event: Event) => { setServerUrl((event.target as HTMLInputElement).value); setNotice(undefined) },
          }),
          React.createElement('p', null, t('serverUrlHint'))),
        role === 'host' ? React.createElement('div', { className: 'dshRemoteAuthMethod' },
          React.createElement('span', { className: 'dshRemoteFieldLabel' }, t('authorizationMethod')),
          React.createElement('div', { className: 'dshRemoteAuthTabs', role: 'tablist', 'aria-label': t('authorizationMethod') },
            React.createElement('button', {
              type: 'button',
              role: 'tab',
              id: 'dsh-remote-auth-account-tab',
              className: hostEnrollment === 'account' ? 'isActive' : '',
              'aria-selected': hostEnrollment === 'account',
              'aria-controls': 'dsh-remote-auth-account-panel',
              disabled: busy || !writable,
              onClick: () => { setHostEnrollment('account'); setNotice(undefined); setError(undefined) },
            }, t('accountPassword')),
            React.createElement('button', {
              type: 'button',
              role: 'tab',
              id: 'dsh-remote-auth-code-tab',
              className: hostEnrollment === 'host_registration_code' ? 'isActive' : '',
              'aria-selected': hostEnrollment === 'host_registration_code',
              'aria-controls': 'dsh-remote-auth-code-panel',
              disabled: busy || !writable,
              onClick: () => { setHostEnrollment('host_registration_code'); setNotice(undefined); setError(undefined) },
            }, t('registrationCode')))) : null,
        role === 'host' && hostEnrollment === 'host_registration_code'
          ? React.createElement('div', {
            className: 'dshRemoteAuthPanel',
            role: 'tabpanel',
            id: 'dsh-remote-auth-code-panel',
            'aria-labelledby': 'dsh-remote-auth-code-tab',
          },
            React.createElement('div', { className: 'dshRemoteField' },
              React.createElement('label', { htmlFor: 'dsh-remote-registration-code' }, t('hostRegistrationCode')),
              React.createElement('input', {
                id: 'dsh-remote-registration-code',
                value: registrationCode,
                disabled: busy || !writable,
                required: true,
                autoComplete: 'one-time-code',
                placeholder: 'ABCD-EFGH',
                onChange: (event: Event) => { setRegistrationCode((event.target as HTMLInputElement).value); setNotice(undefined) },
              }),
              React.createElement('p', null, t('registrationCodeHint'))))
          : React.createElement('div', {
            className: 'dshRemoteAuthPanel',
            role: role === 'host' ? 'tabpanel' : undefined,
            id: role === 'host' ? 'dsh-remote-auth-account-panel' : undefined,
            'aria-labelledby': role === 'host' ? 'dsh-remote-auth-account-tab' : undefined,
          },
            React.createElement('div', { className: 'dshRemoteField' },
              React.createElement('label', { htmlFor: 'dsh-remote-account' }, t('account')),
              React.createElement('input', {
                id: 'dsh-remote-account',
                type: 'email',
                value: email,
                disabled: busy || !writable,
                required: true,
                autoComplete: 'username',
                onChange: (event: Event) => { setEmail((event.target as HTMLInputElement).value); setNotice(undefined) },
              }),
              React.createElement('p', null, t('accountHint'))),
            React.createElement('div', { className: 'dshRemoteField' },
              React.createElement('label', { htmlFor: 'dsh-remote-password' }, t('password')),
              React.createElement('input', {
                id: 'dsh-remote-password',
                type: 'password',
                value: password,
                disabled: busy || !writable,
                required: true,
                autoComplete: 'current-password',
                onChange: (event: Event) => { setPassword((event.target as HTMLInputElement).value); setNotice(undefined) },
              }),
              React.createElement('p', null, t('passwordHint')))),
        !writable ? React.createElement('p', { className: 'dshRemoteError' }, t('readOnly')) : null,
        React.createElement('div', { className: 'dshRemoteSettingsFooter' },
          error !== undefined
            ? React.createElement('p', { className: 'dshRemoteError', role: 'alert' }, error)
            : notice === undefined ? null : React.createElement('p', { className: 'dshRemoteNotice', role: 'status' }, t(notice.key, notice.params)),
          React.createElement('button', { type: 'button', className: 'dshRemoteDiscard', disabled: busy || !draftDirty, onClick: discard }, t('discard')),
          React.createElement('button', { type: 'submit', className: 'dshRemoteSave', disabled: busy || !writable || !draftDirty }, t(busy ? 'saving' : 'save'))))))
    }

    function RemoteModeAction(props: {
      wide: boolean
      control: <T>(endpoint: string, payload?: unknown) => Promise<T>
      t: Translate
    }): unknown {
      const { t } = props
      const [open, setOpen] = React.useState(false)
      const [status, setStatus] = React.useState<RemoteStatus | undefined>(undefined)
      const [devices, setDevices] = React.useState<RemoteDevice[]>([])
      const [hostRegistrationCode, setHostRegistrationCode] = React.useState('')
      const [email, setEmail] = React.useState('')
      const [password, setPassword] = React.useState('')
      const [busy, setBusy] = React.useState(false)
      const [error, setError] = React.useState<string | undefined>(undefined)
      const [supported, setSupported] = React.useState(true)

      const refresh = async (): Promise<void> => {
        const [nextStatus, nextDevices] = await Promise.all([
          props.control<RemoteStatus>('status'),
          props.control<RemoteDevice[]>('devices').catch(() => []),
        ])
        setStatus(nextStatus)
        setDevices(nextDevices)
      }

      const refreshStatus = async (): Promise<void> => {
        setStatus(await props.control<RemoteStatus>('status'))
      }

      React.useEffect(() => {
        void refresh().catch(reason => {
          setError(messageOf(reason))
          setSupported(false)
        })
      }, [])

      React.useEffect(() => {
        if (!open) return
        void refreshStatus()
        const timer = window.setInterval(() => {
          void refreshStatus()
        }, 1500)
        return () => window.clearInterval(timer)
      }, [open])

      const switchMode = async (mode: 'local' | 'remote', targetDeviceId?: string): Promise<void> => {
        setBusy(true)
        setError(undefined)
        try {
          await props.control('mode.set', { mode, ...(targetDeviceId === undefined ? {} : { targetDeviceId }) })
          window.location.reload()
        } catch (reason) {
          setError(messageOf(reason))
          setBusy(false)
        }
      }

      const loginHost = async (): Promise<void> => {
        if (email.trim() === '' || password === '') return
        setBusy(true)
        setError(undefined)
        try {
          await props.control('host.account.login', { email: email.trim(), password })
          await refreshStatus()
        } catch (reason) {
          setError(messageOf(reason))
        } finally {
          setPassword('')
          setBusy(false)
        }
      }

      const registerHostWithCode = async (): Promise<void> => {
        if (hostRegistrationCode.trim() === '') return
        setBusy(true)
        setError(undefined)
        try {
          await props.control('host.registration-code.submit', { code: hostRegistrationCode.trim() })
          setHostRegistrationCode('')
          await refreshStatus()
        } catch (reason) {
          setError(messageOf(reason))
        } finally {
          setBusy(false)
        }
      }

      const label = status?.mode === 'remote'
        ? t('remoteTarget', { name: status.target?.name ?? t('host') })
        : t('local')
      if (!supported) return null
      return React.createElement(React.Fragment, null,
        React.createElement('button', {
          type: 'button',
          className: 'dshRemoteModeButton',
          title: t('switchTarget'),
          'aria-label': t('switchTarget'),
          onClick: () => setOpen(true),
        }, React.createElement('span', { 'aria-hidden': true }, '◎'), props.wide
          ? React.createElement('span', null, label)
          : null),
        open ? React.createElement('div', { className: 'dshRemoteBackdrop', role: 'presentation' },
          React.createElement('section', {
            className: 'dshRemoteDialog',
            role: 'dialog',
            'aria-modal': true,
            'aria-label': t('harnessTarget'),
          },
          React.createElement('div', { className: 'dshRemoteHeader' },
            React.createElement('strong', null, t('harnessTarget')),
            React.createElement('button', { type: 'button', onClick: () => setOpen(false), 'aria-label': t('close') }, '×')),
          React.createElement('button', {
            type: 'button',
            disabled: busy || status?.mode === 'local',
            onClick: () => void switchMode('local'),
          }, t('thisMachineLocal')),
          React.createElement('div', { className: 'dshRemoteDevices' }, devices.length === 0
            ? React.createElement('p', null, t('noRemoteHosts'))
            : devices.map(device => React.createElement('button', {
              type: 'button',
              key: device.deviceId,
              disabled: busy || !device.online || status?.target?.deviceId === device.deviceId,
              onClick: () => void switchMode('remote', device.deviceId),
            }, `${device.name} · ${t(device.online ? 'online' : 'offline')}`))),
          status?.hostAuthorizationAvailable && status.host !== undefined
            ? React.createElement('div', { className: 'dshRemoteHostAccount' },
              React.createElement('strong', null, t('thisMachineHost')),
              React.createElement('p', null, status.host.online
                ? status.host.account === undefined ? t('connected') : t('connectedAs', { account: status.host.account })
                : status.host.accountRequired
                  ? t('hostSignInHint')
                  : status.host.error === undefined
                    ? t('checkingHost')
                    : t('hostUnavailable', { error: status.host.error })),
              status.host.accountRequired ? React.createElement('div', { className: 'dshRemoteLogin' },
                React.createElement('input', {
                  type: 'email',
                  value: email,
                  disabled: busy,
                  autoComplete: 'username',
                  placeholder: t('serverAccountEmail'),
                  'aria-label': t('serverAccountEmail'),
                  onChange: (event: Event) => setEmail((event.target as HTMLInputElement).value),
                }),
                React.createElement('input', {
                  type: 'password',
                  value: password,
                  disabled: busy,
                  autoComplete: 'current-password',
                  placeholder: t('password'),
                  'aria-label': t('serverAccountPassword'),
                  onChange: (event: Event) => setPassword((event.target as HTMLInputElement).value),
                }),
                React.createElement('button', {
                  type: 'button',
                  disabled: busy || email.trim() === '' || password === '',
                  onClick: () => void loginHost(),
                }, t(busy ? 'signingIn' : 'signInRegisterHost')),
                React.createElement('input', {
                  value: hostRegistrationCode,
                  disabled: busy,
                  autoComplete: 'one-time-code',
                  placeholder: t('hostRegistrationCode'),
                  'aria-label': t('hostRegistrationCode'),
                  onChange: (event: Event) => setHostRegistrationCode((event.target as HTMLInputElement).value),
                }),
                React.createElement('button', {
                  type: 'button',
                  disabled: busy || hostRegistrationCode.trim() === '',
                  onClick: () => void registerHostWithCode(),
                }, t(busy ? 'registering' : 'useRegistrationCode'))) : null)
            : null,
          error === undefined ? null : React.createElement('p', { className: 'dshRemoteError', role: 'alert' }, error)))
          : null)
    }

    function installStyle(): () => void {
      const style = document.createElement('style')
      style.dataset.pluginCss = '@dsh-remote/plugin'
      style.textContent = [
        '.dshRemoteModeButton{min-height:36px;border:0;background:transparent;color:var(--dsw-alias-label-primary);display:flex;align-items:center;gap:8px;padding:0 10px;border-radius:8px;cursor:pointer}',
        '.dshRemoteModeButton:hover{background:var(--dsw-alias-interactive-bg-hover)}',
        '.dshRemoteBackdrop{position:fixed;inset:0;z-index:1000;background:rgba(0,0,0,.42);display:grid;place-items:center;padding:20px}',
        '.dshRemoteDialog{width:min(460px,100%);max-height:80vh;overflow:auto;background:var(--dsw-alias-bg-primary,#fff);color:var(--dsw-alias-label-primary);border:1px solid var(--dsw-alias-border-l2);border-radius:14px;padding:18px;display:grid;gap:12px;box-shadow:0 18px 60px rgba(0,0,0,.28)}',
        '.dshRemoteDialog button,.dshRemoteDialog input{font:inherit;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;padding:9px 10px;background:transparent;color:inherit}',
        '.dshRemoteDialog button:not(:disabled){cursor:pointer}.dshRemoteDialog button:disabled{opacity:.5}',
        '.dshRemoteHeader{display:flex;align-items:center;justify-content:space-between}.dshRemoteHeader button{border:0;font-size:22px;padding:0 6px}',
        '.dshRemoteDevices{display:grid;gap:8px}.dshRemoteDevices p{margin:4px 0;color:var(--dsw-alias-label-secondary)}',
        '.dshRemoteError{margin:0;color:var(--dsw-alias-state-danger,#c33)}',
        '.dshRemoteHostAccount{display:grid;gap:8px;border-top:1px solid var(--dsw-alias-border-l3);padding-top:12px}.dshRemoteHostAccount p{margin:0;color:var(--dsw-alias-label-secondary);font-size:13px}',
        '.dshRemoteLogin{display:grid;grid-template-columns:1fr 1fr;gap:8px}.dshRemoteLogin button{grid-column:1/-1}',
        '.dshRemotePluginCard{list-style:none;border:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-layer-3);border-radius:12px;transition:border-color .16s,background .16s}',
        '.dshRemotePluginCard:hover{border-color:var(--dsw-alias-label-dimmed)}.dshRemotePluginCard.isOpen{background:var(--dsw-alias-bg-layer-2);border-color:var(--dsw-alias-label-dimmed)}',
        '.dshRemotePluginCardHeader{display:flex;align-items:center}.dshRemotePluginCardToggle{appearance:none;width:100%;min-width:0;font:inherit;color:inherit;text-align:left;cursor:pointer;background:transparent;border:0;border-radius:12px;display:flex;align-items:center;gap:12px;padding:14px 16px}.dshRemotePluginCardToggle:focus-visible{outline:2px solid var(--dsw-alias-brand-primary);outline-offset:-2px}',
        '.dshRemotePluginCardHeading{display:flex;flex-direction:column;gap:4px;min-width:0;flex:1}.dshRemotePluginCardHeading>strong{color:var(--dsw-alias-label-primary);font-size:15px;font-weight:600;line-height:1.4}.dshRemotePluginCardHeading>span{color:var(--dsw-alias-label-tertiary);font-size:13px;line-height:1.5}.dshRemotePluginCardStatus{white-space:nowrap;background:var(--dsw-alias-bg-module-platform);color:var(--dsw-alias-label-secondary);border-radius:999px;padding:1px 8px;font-size:11px;font-weight:500;line-height:17px}.dshRemotePluginCardChevron{color:var(--dsw-alias-label-tertiary);font-size:18px;line-height:14px;transition:transform .16s}.dshRemotePluginCard.isOpen .dshRemotePluginCardChevron{transform:rotate(180deg)}',
        '.dshRemoteRoleField{display:flex;align-items:center;gap:6px;flex:none}.dshRemoteRoleLabel{color:var(--dsw-alias-label-tertiary);font-size:12px}.dshRemoteRoleSwitch{height:30px;border:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-layer-3);border-radius:8px;display:flex;padding:2px}.dshRemoteRoleSwitch button{appearance:none;min-width:52px;border:0;border-radius:6px;background:transparent;color:var(--dsw-alias-label-tertiary);font:inherit;font-size:12px;line-height:24px;padding:0 8px;cursor:pointer}.dshRemoteRoleSwitch button:hover:not(:disabled){color:var(--dsw-alias-label-primary)}.dshRemoteRoleSwitch button.isActive{background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-primary);font-weight:600}.dshRemoteRoleSwitch button:focus-visible{outline:2px solid var(--dsw-alias-brand-primary);outline-offset:0}.dshRemoteRoleSwitch button:disabled{cursor:default;opacity:.45}',
        '.dshRemotePluginCardBody{border-top:1px solid var(--dsw-alias-border-l2);margin:0 16px;padding-bottom:8px}.dshRemoteSettings{display:flex;flex-direction:column;max-width:720px}.dshRemoteSettingsTop{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;padding:12px 0}.dshRemoteSettingsIntro{min-width:0;flex:1}.dshRemoteSettingsIntro p,.dshRemoteSettingsState{margin:0;color:var(--dsw-alias-label-tertiary);font-size:13px;line-height:1.5}',
        '.dshRemoteAuthPanel{display:flex;flex-direction:column}.dshRemoteField,.dshRemoteAuthMethod{display:flex;flex-direction:column;gap:6px;padding:12px 0}.dshRemoteField+.dshRemoteField,.dshRemoteField+.dshRemoteAuthMethod,.dshRemoteAuthMethod+.dshRemoteField,.dshRemoteAuthMethod+.dshRemoteAuthPanel>.dshRemoteField:first-child{border-top:1px solid var(--dsw-alias-border-l2)}.dshRemoteField label,.dshRemoteFieldLabel{color:var(--dsw-alias-label-primary);font-size:13px;font-weight:500;line-height:1.5}.dshRemoteField input{border:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-layer-3);height:34px;font:inherit;color:var(--dsw-alias-label-primary);border-radius:8px;padding:0 12px;font-size:13px;line-height:1.5}.dshRemoteField input:focus-visible{border-color:var(--dsw-alias-brand-primary);outline:none}.dshRemoteField input:disabled{color:var(--dsw-alias-label-tertiary);cursor:default}.dshRemoteField p{color:var(--dsw-alias-label-tertiary);margin:0;font-size:12px;line-height:1.5}',
        '.dshRemoteAuthTabs{align-self:flex-start;border:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-layer-3);border-radius:8px;display:flex;padding:2px}.dshRemoteAuthTabs button{appearance:none;border:0;border-radius:6px;background:transparent;color:var(--dsw-alias-label-tertiary);font:inherit;font-size:13px;line-height:28px;padding:0 12px;cursor:pointer}.dshRemoteAuthTabs button:hover:not(:disabled){color:var(--dsw-alias-label-primary)}.dshRemoteAuthTabs button.isActive{background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-primary);font-weight:500}.dshRemoteAuthTabs button:focus-visible{outline:2px solid var(--dsw-alias-brand-primary);outline-offset:0}.dshRemoteAuthTabs button:disabled{cursor:default;opacity:.45}',
        '.dshRemoteAssociation{min-width:0;flex:1;display:flex;flex-direction:column;gap:4px}.dshRemoteAssociation>span{color:var(--dsw-alias-label-tertiary);font-size:12px;line-height:1.5}.dshRemoteAssociation strong{color:var(--dsw-alias-label-primary);font-size:14px;font-weight:500;line-height:1.5}.dshRemoteAssociation p{color:var(--dsw-alias-label-tertiary);margin:0;font-size:12px;line-height:1.5}',
        '.dshRemoteSettingsFooter{border-top:1px solid var(--dsw-alias-border-l2);display:flex;justify-content:flex-end;align-items:center;gap:8px;padding:12px 0 4px}.dshRemoteSettingsFooter .dshRemoteError,.dshRemoteNotice{min-width:0;flex:1;margin:0;font-size:12px;line-height:1.5}.dshRemoteNotice{color:var(--dsw-alias-label-tertiary)}.dshRemoteDiscard,.dshRemoteSave{appearance:none;font:inherit;cursor:pointer;border:1px solid transparent;border-radius:8px;padding:5px 14px;font-size:13px;line-height:1.5}.dshRemoteDiscard{border-color:var(--dsw-alias-border-l2);color:var(--dsw-alias-label-secondary);background:transparent}.dshRemoteDiscard:hover:not(:disabled){color:var(--dsw-alias-label-primary);border-color:var(--dsw-alias-label-dimmed)}.dshRemoteSave{background:var(--dsw-alias-label-primary);color:var(--dsw-alias-bg-layer-3)}.dshRemoteDiscard:disabled,.dshRemoteSave:disabled{opacity:.4;cursor:default}.dshRemoteDiscard:focus-visible,.dshRemoteSave:focus-visible{outline:2px solid var(--dsw-alias-brand-primary);outline-offset:1px}',
        '@media(max-width:620px){.dshRemotePluginCardStatus{display:none}.dshRemoteSettingsTop{gap:10px}.dshRemoteRoleLabel{display:none}.dshRemoteRoleSwitch button{min-width:46px;padding:0 6px}.dshRemoteAuthTabs{align-self:stretch}.dshRemoteAuthTabs button{flex:1;padding:0 8px}}',
      ].join('')
      document.head.append(style)
      return () => style.remove()
    }

    function apply(ctx: {
      connection: { rpc: { call(channel: string, endpoint: string, payload: unknown): Promise<ControlResult> } }
      effect(effect: () => (() => void), label: string): void
      locale: {
        bind(namespace: string): Translate
        register(namespace: string, dictionaries: { zh: typeof zh; en: typeof en }): () => void
      }
      slots: {
        inject(name: string, factory: () => unknown): void
        register(options: Record<string, unknown>, component: unknown): unknown
      }
    }): void {
      const t = ctx.locale.bind(localeNamespace)
      const control = async <T,>(endpoint: string, payload: unknown = {}): Promise<T> => {
        let result: ControlResult
        for (let attempt = 0; ; attempt += 1) {
          try {
            result = await ctx.connection.rpc.call('/remote', endpoint, payload)
            break
          } catch (reason) {
            // The browser face can mount one turn before the injected Host
            // runtime has registered /remote. A 405 comes from the static Web
            // fallback, so the RPC was not dispatched and is safe to retry.
            if (attempt >= 19 || !isPendingControlRoute(reason)) throw reason
            await delay(100)
          }
        }
        if (!result.ok) throw new Error(result.error?.message ?? t('remoteRequestFailed'))
        return result.value as T
      }
      ctx.effect(() => ctx.locale.register(localeNamespace, { zh, en }), 'dsh-remote: dictionaries')
      ctx.effect(installStyle, 'dsh-remote: client styles')
      ctx.slots.inject('sidebar.footer.action', () => ctx.slots.register({
        name: 'sidebar.footer.action',
        id: 'dsh-remote-mode',
        order: -20,
        locale: localeNamespace,
        inject: () => ({ control }),
      }, RemoteModeAction))
      ctx.slots.inject('settings.plugin.item', () => ctx.slots.register({
        name: 'settings.plugin.item',
        id: 'dsh-remote',
        order: 30,
        locale: localeNamespace,
        inject: () => ({ control }),
      }, RemotePluginOptions))
    }

    function isPendingControlRoute(reason: unknown): boolean {
      return reason instanceof Error && /transport failure for \/remote\/[^:]+: HTTP 405$/.test(reason.message)
    }

    function delay(ms: number): Promise<void> {
      return new Promise(resolve => window.setTimeout(resolve, ms))
    }

    function messageOf(reason: unknown): string { return reason instanceof Error ? reason.message : String(reason) }

    module.exports.apply = apply
    module.exports.inject = inject
    return module.exports
  },
})
